# Generated by Django 3.1.4 on 2020-12-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=6, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
